### PR TITLE
Add ability to merge with master branch

### PR DESCRIPTION
**Pull request by eirnym**
This change provides an ability to merge with master branch from `funkyfuture` and `pyeve`.

Please, review all changes. I tried to make the merge as accurate as possible, but could done mistakes. 

not passing (as probably wasn't in `forward`):

```
FAILED cerberus/tests/test_schema.py::test_unknown_rule
FAILED cerberus/tests/test_schema.py::test_unknown_type
```

### CODE REVIEW

**Comment by funkyfuture** [comment]
no, it's not that easy. what you probably should do (or i would later):

- make a new branch off the `master`
- cherry-pick and adjust(!) the commits from the `forward` branch in order

**Comment by eirnym** [comment]
I did the merge of your branch to the master. Is it wrong way to do it?

**Comment by funkyfuture** [comment]
yes, because the `forward` branch is missing commits from the `master` branch and eventually the `forward`-commits shall appear after them in the git history, as the `forward` branch originally did.

so, usually a `rebase` would be necessary, but in this case `cherry-pick`ing individually is preferable for the nervous system. (rebasing is essentially a bulk of cherry-picking.)

if you're unfamiliar with rebasing and cherry-picking, take your time to learn and practise it. it took me some time to use these tools safely, but it is certainly worth it to know these.

**Comment by eirnym** [comment]
I thought you want to merge it (as it was said in the original PR). I'll do the rebase.

**Comment by funkyfuture** [comment]
if you want to take this challenge, please

- open a PR on the `pyeve` repo where the `master` branch is up-to-date
- begin with one commit from the `forward` branch, so i can review one commit at a time

the resulting PR must have only the commits from the `forward` branch on top of 688a67a4069e88042ed424bda7be0f4fa5fc3910. nothing else that has already been merged like in this PR here.

**Comment by eirnym** [comment]
no sense with this branch anymore. Rebased to `pyeve`

**Pull request closed without merging**
